version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "3000:80"
  cms:
    image: "agentejo/cockpit:latest"
    ports:
      - "8080:80"